//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karambolo.PO.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karambolo.PO.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header has multiple items with key &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicateHeaderKey {
            get {
                return ResourceManager.GetString("DuplicateHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry beginning at {0} has multiple plural form with index {0}..
        /// </summary>
        internal static string DuplicatePluralForm {
            get {
                return ResourceManager.GetString("DuplicatePluralForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding of writer and catalog should match. However, you may disable this check by setting POGeneratorSettings.IgnoreEncoding to true..
        /// </summary>
        internal static string EncodingMismatch {
            get {
                return ResourceManager.GetString("EncodingMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO specification allows only single-byte encodings so writer should use a single-byte encoding, too. However, you may disable this check by setting POGeneratorSettings.IgnoreEncoding to true..
        /// </summary>
        internal static string EncodingNotSingleByte {
            get {
                return ResourceManager.GetString("EncodingNotSingleByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry beginning at {0} has an empty id..
        /// </summary>
        internal static string EntryHasEmptyId {
            get {
                return ResourceManager.GetString("EntryHasEmptyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token &apos;{1}&apos; is expected at {0}..
        /// </summary>
        internal static string ExpectedToken {
            get {
                return ResourceManager.GetString("ExpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header must be a singular entry..
        /// </summary>
        internal static string HeaderNotSingular {
            get {
                return ResourceManager.GetString("HeaderNotSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry beginning at {0} is incomplete..
        /// </summary>
        internal static string IncompleteEntry {
            get {
                return ResourceManager.GetString("IncompleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was not in a correct format..
        /// </summary>
        internal static string IncorrectFormat {
            get {
                return ResourceManager.GetString("IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry has an invalid key. {0} must be non-null and can be empty only if {1} or {2} is non-null, i.e. key is not the reserved header entry key..
        /// </summary>
        internal static string InvalidCatalogEntryKey {
            get {
                return ResourceManager.GetString("InvalidCatalogEntryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid control character encountered at {0}..
        /// </summary>
        internal static string InvalidControlChar {
            get {
                return ResourceManager.GetString("InvalidControlChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry beginning at {0} has an invalid key..
        /// </summary>
        internal static string InvalidEntryKey {
            get {
                return ResourceManager.GetString("InvalidEntryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequence is invalid at {0}..
        /// </summary>
        internal static string InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header entry should have only translator comments..
        /// </summary>
        internal static string InvalidHeaderComment {
            get {
                return ResourceManager.GetString("InvalidHeaderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header value &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidHeaderValue {
            get {
                return ResourceManager.GetString("InvalidHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is invalid. {0} must be non-null and {1} must be non-null..
        /// </summary>
        internal static string InvalidPluralEntryKey {
            get {
                return ResourceManager.GetString("InvalidPluralEntryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural index is invalid at {0}..
        /// </summary>
        internal static string InvalidPluralIndex {
            get {
                return ResourceManager.GetString("InvalidPluralIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is invalid. {0} must be non-null and {1} must be null..
        /// </summary>
        internal static string InvalidSingularEntryKey {
            get {
                return ResourceManager.GetString("InvalidSingularEntryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment at {0} is in the wrong format..
        /// </summary>
        internal static string MalformedComment {
            get {
                return ResourceManager.GetString("MalformedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header &apos;{0}&apos; is in the wrong format..
        /// </summary>
        internal static string MalformedHeaderItem {
            get {
                return ResourceManager.GetString("MalformedHeaderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry beginning at {0} has no plural form with index {1}..
        /// </summary>
        internal static string MissingPluralForm {
            get {
                return ResourceManager.GetString("MissingPluralForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural index is missing at {0}..
        /// </summary>
        internal static string MissingPluralIndex {
            get {
                return ResourceManager.GetString("MissingPluralIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token at {0} is unexpected..
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural index at {0} is unnecessary..
        /// </summary>
        internal static string UnnecessaryPluralIndex {
            get {
                return ResourceManager.GetString("UnnecessaryPluralIndex", resourceCulture);
            }
        }
    }
}
